//
// Created by QinBu_Rua on 2026/2/23.
//

#ifndef AUTO_SORTING_MACHINE_INCLUDES_CLASSES_NAVIEBAYESMODEL_H
#define AUTO_SORTING_MACHINE_INCLUDES_CLASSES_NAVIEBAYESMODEL_H


namespace QinBuRua::auto_sorting_machine {

class NavieBayesModel {

};

}


#endif //AUTO_SORTING_MACHINE_INCLUDES_CLASSES_NAVIEBAYESMODEL_H
